import { TransportInterface } from './Transport/TransportInterface';
import { RegisterOptions } from './Observable/RegisterObservable';
import { PublishOptions, TopicOptions } from './Observable/TopicObservable';
import { ChallengeMessage } from './Messages/ChallengeMessage';
import { CallOptions } from './Observable/CallObservable';
import { ResultMessage } from './Messages/ResultMessage';
import { RegisteredMessage } from './Messages/RegisteredMessage';
import { UnregisteredMessage } from './Messages/UnregisteredMessage';
import { EventMessage } from './Messages/EventMessage';
import { IMessage } from './Messages/Message';
import { Observable } from 'rxjs/Observable';
import { Subscription } from 'rxjs/Subscription';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/take';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/merge';
import 'rxjs/add/operator/take';
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/mapTo';
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/retryWhen';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/switchMapTo';
import 'rxjs/add/operator/takeUntil';
import 'rxjs/add/operator/takeWhile';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/publishReplay';
import 'rxjs/add/operator/publish';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/finally';
import 'rxjs/add/operator/exhaust';
import 'rxjs/add/operator/defaultIfEmpty';
import 'rxjs/add/operator/multicast';
import 'rxjs/add/operator/shareReplay';
import 'rxjs/add/observable/empty';
import 'rxjs/add/observable/from';
import 'rxjs/add/observable/timer';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/merge';
import 'rxjs/add/observable/throw';
export declare class Client {
    private urlOrTransport;
    private realm;
    private options;
    private transport;
    private messages;
    private subscription;
    private _session;
    private _onClose;
    private challengeCallback;
    private currentRetryCount;
    private static roles();
    constructor(urlOrTransport: string | TransportInterface, realm: string, options?: WampOptions, transport?: TransportInterface);
    topic(uri: string, options?: TopicOptions): Observable<EventMessage>;
    publish<T>(uri: string, value: Observable<T> | any, options?: PublishOptions): Subscription;
    call(uri: string, args?: Array<any>, argskw?: Object, options?: CallOptions): Observable<ResultMessage>;
    register(uri: string, callback: Function, options?: RegisterOptions): Observable<RegisteredMessage | UnregisteredMessage>;
    progressiveCall(uri: string, args?: Array<any>, argskw?: Object, options?: CallOptions): Observable<ResultMessage>;
    progressiveRegister(uri: string, callback: Function, options?: RegisterOptions): Observable<any>;
    onChallenge(challengeCallback: (challenge: Observable<ChallengeMessage>) => Observable<string>): void;
    close(): void;
    readonly onOpen: Observable<IMessage>;
    readonly onClose: Observable<IMessage>;
}
export interface WampOptions {
    authmethods?: Array<string>;
    roles?: Object;
    role?: string;
    [propName: string]: any;
}
